# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'
platform :ios, '10.0'

target 'Music' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Music
  pod 'R_category', '0.0.8'
  pod 'Moya', '13.0.1'
  pod 'Kingfisher', '5.7.1'
  pod 'SnapKit'
  
end
